<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>FlightTrackerBridge</AssemblyName>
    <RootNamespace>FlightTracker.PC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FSUIPCClientDLL" Version="3.3.16" />
  </ItemGroup>

</Project>
